export type DayId = "VEN" | "SAM" | "DIM";

export type FestivalEvent = {
  id: string;
  title: string;
  artist: string;
  speakers: string[];
  category: "concerts" | "conferences" | "activites" | "stands";
  genre: string;
  genreId: string;
  origin: string;
  day: DayId;
  dateLabel: string;
  startsAt: string;
  endsAt: string;
  time: string;
  duration: string;
  stage: string;
  address: string;
  latitude: number;
  longitude: number;
  description: string;
  image: string;
  dateBg: string;
  dateText: string;
  accent: string;
  hoverBorder: string;
};

const commonLocation = {
  address: "Fatal Fields, Ardennes, France",
};

export const fallbackFestivalEvents: FestivalEvent[] = [
  {
    id: "bain-glace-guide",
    title: "Bain de glace guide",
    artist: "Collectif Cryo",
    speakers: ["Maya Renard", "Collectif Cryo"],
    category: "activites",
    genre: "Bien-etre extreme",
    genreId: "bien-etre",
    origin: "FR",
    day: "VEN",
    dateLabel: "VEN 24",
    startsAt: "2027-01-24T18:00:00+01:00",
    endsAt: "2027-01-24T19:00:00+01:00",
    time: "18:00",
    duration: "1H",
    stage: "Zone Cryo",
    ...commonLocation,
    latitude: 49.7614,
    longitude: 4.7168,
    description:
      "Initiation encadree a l'immersion froide, avec preparation respiratoire et equipe medicale a proximite.",
    image: "/event_3.png",
    dateBg: "bg-cyan",
    dateText: "text-dark",
    accent: "text-cyan",
    hoverBorder: "group-hover:[border-top-color:#00f5ff]",
  },
  {
    id: "2nd-gen",
    title: "Ouverture Glitch",
    artist: "2nd-Gen",
    speakers: ["2nd-Gen"],
    category: "concerts",
    genre: "Glitch Ambient",
    genreId: "dark-ambient",
    origin: "FR",
    day: "VEN",
    dateLabel: "VEN 24",
    startsAt: "2027-01-24T22:00:00+01:00",
    endsAt: "2027-01-24T23:45:00+01:00",
    time: "22:00",
    duration: "1H45",
    stage: "Sanctuaire de Glace",
    ...commonLocation,
    latitude: 49.7621,
    longitude: 4.7185,
    description:
      "Une plongee dans le glitch ambient, entre textures numeriques fracturees, drones hypnotiques et derive algorithmique.",
    image: "/event_3.png",
    dateBg: "bg-cyan",
    dateText: "text-dark",
    accent: "text-cyan",
    hoverBorder: "group-hover:[border-top-color:#00f5ff]",
  },
  {
    id: "neve",
    title: "Neve Live",
    artist: "Neve",
    speakers: ["Neve"],
    category: "concerts",
    genre: "Techno Hypnotique",
    genreId: "techno",
    origin: "BE",
    day: "VEN",
    dateLabel: "VEN 24",
    startsAt: "2027-01-24T23:30:00+01:00",
    endsAt: "2027-01-25T01:00:00+01:00",
    time: "23:30",
    duration: "1H30",
    stage: "Scene Glacier",
    ...commonLocation,
    latitude: 49.763,
    longitude: 4.7202,
    description:
      "Une techno hypnotique concue pour accompagner la tombee de la nuit et faire vibrer la scene Glacier.",
    image: "/event_1.png",
    dateBg: "bg-cyan",
    dateText: "text-dark",
    accent: "text-cyan",
    hoverBorder: "group-hover:[border-top-color:#00f5ff]",
  },
  {
    id: "whiteout",
    title: "Whiteout",
    artist: "Whiteout",
    speakers: ["Whiteout"],
    category: "concerts",
    genre: "Drone / Noise",
    genreId: "dark-ambient",
    origin: "IS",
    day: "VEN",
    dateLabel: "VEN 24",
    startsAt: "2027-01-25T01:00:00+01:00",
    endsAt: "2027-01-25T02:15:00+01:00",
    time: "01:00",
    duration: "1H15",
    stage: "Zone Cryo",
    ...commonLocation,
    latitude: 49.7614,
    longitude: 4.7168,
    description:
      "Un mur de drone et de noise inspire des paysages islandais, joue au coeur de la zone Cryo.",
    image: "/Event_2.png",
    dateBg: "bg-cyan",
    dateText: "text-dark",
    accent: "text-cyan",
    hoverBorder: "group-hover:[border-top-color:#00f5ff]",
  },
  {
    id: "consentement-espace-public",
    title: "Corps, consentement et espace public",
    artist: "Elise Martin",
    speakers: ["Dr Elise Martin", "Nora Klein"],
    category: "conferences",
    genre: "Table ronde",
    genreId: "table-ronde",
    origin: "FR",
    day: "SAM",
    dateLabel: "SAM 25",
    startsAt: "2027-01-25T15:00:00+01:00",
    endsAt: "2027-01-25T16:30:00+01:00",
    time: "15:00",
    duration: "1H30",
    stage: "Agora Thermique",
    ...commonLocation,
    latitude: 49.7608,
    longitude: 4.7198,
    description:
      "Une table ronde sur le consentement, la liberte corporelle et la construction d'espaces festifs respectueux.",
    image: "/Event_2.png",
    dateBg: "bg-lime",
    dateText: "text-dark",
    accent: "text-lime",
    hoverBorder: "group-hover:[border-top-color:#c8ff00]",
  },
  {
    id: "frontex",
    title: "Frontex",
    artist: "Frontex",
    speakers: ["Frontex"],
    category: "concerts",
    genre: "Techno Industrielle",
    genreId: "industrial",
    origin: "DE",
    day: "SAM",
    dateLabel: "SAM 25",
    startsAt: "2027-01-25T23:00:00+01:00",
    endsAt: "2027-01-26T01:00:00+01:00",
    time: "23:00",
    duration: "2H",
    stage: "Scene Glacier",
    ...commonLocation,
    latitude: 49.763,
    longitude: 4.7202,
    description:
      "Frontex transforme l'acier et la glace en arme sonique avec des rythmiques industrielles sans compromis.",
    image: "/event_1.png",
    dateBg: "bg-lime",
    dateText: "text-dark",
    accent: "text-lime",
    hoverBorder: "group-hover:[border-top-color:#c8ff00]",
  },
  {
    id: "permafrost",
    title: "Permafrost",
    artist: "Permafrost",
    speakers: ["Permafrost"],
    category: "concerts",
    genre: "EBM / Power",
    genreId: "electro",
    origin: "SE",
    day: "SAM",
    dateLabel: "SAM 25",
    startsAt: "2027-01-26T00:30:00+01:00",
    endsAt: "2027-01-26T02:00:00+01:00",
    time: "00:30",
    duration: "1H30",
    stage: "Zone Cryo",
    ...commonLocation,
    latitude: 49.7614,
    longitude: 4.7168,
    description:
      "EBM nordique, basses tendues et performance physique dans l'espace le plus froid du festival.",
    image: "/event_3.png",
    dateBg: "bg-lime",
    dateText: "text-dark",
    accent: "text-lime",
    hoverBorder: "group-hover:[border-top-color:#c8ff00]",
  },
  {
    id: "blizzard",
    title: "Blizzard",
    artist: "Blizzard",
    speakers: ["Blizzard"],
    category: "concerts",
    genre: "Metal Experimental",
    genreId: "metal",
    origin: "FI",
    day: "SAM",
    dateLabel: "SAM 25",
    startsAt: "2027-01-26T02:00:00+01:00",
    endsAt: "2027-01-26T03:30:00+01:00",
    time: "02:00",
    duration: "1H30",
    stage: "Scene Glacier",
    ...commonLocation,
    latitude: 49.763,
    longitude: 4.7202,
    description:
      "Metal experimental finlandais, nappes abrasives et rythmiques extremes sous le dome geodesique.",
    image: "/Event_2.png",
    dateBg: "bg-lime",
    dateText: "text-dark",
    accent: "text-lime",
    hoverBorder: "group-hover:[border-top-color:#c8ff00]",
  },
  {
    id: "atelier-thermique",
    title: "Atelier textile thermique",
    artist: "Nord Atelier",
    speakers: ["Nord Atelier"],
    category: "stands",
    genre: "Atelier",
    genreId: "atelier",
    origin: "FR",
    day: "DIM",
    dateLabel: "DIM 26",
    startsAt: "2027-01-26T12:00:00+01:00",
    endsAt: "2027-01-26T17:00:00+01:00",
    time: "12:00",
    duration: "5H",
    stage: "Village des stands",
    ...commonLocation,
    latitude: 49.7617,
    longitude: 4.7193,
    description:
      "Decouverte de materiaux thermiques, accessoires reutilisables et conseils pour affronter les zones froides.",
    image: "/event_1.png",
    dateBg: "bg-pink",
    dateText: "text-white",
    accent: "text-pink",
    hoverBorder: "group-hover:[border-top-color:#ff2d9b]",
  },
  {
    id: "king-vibe",
    title: "King Vibe",
    artist: "King Vibe",
    speakers: ["King Vibe"],
    category: "concerts",
    genre: "Experimental Noise",
    genreId: "dark-ambient",
    origin: "NO",
    day: "DIM",
    dateLabel: "DIM 26",
    startsAt: "2027-01-26T02:00:00+01:00",
    endsAt: "2027-01-26T03:30:00+01:00",
    time: "02:00",
    duration: "1H30",
    stage: "Sanctuaire de Glace",
    ...commonLocation,
    latitude: 49.7621,
    longitude: 4.7185,
    description:
      "King Vibe orchestre un chaos de frequences brutes, entre noise experimental et vibrations physiques.",
    image: "/Event_2.png",
    dateBg: "bg-pink",
    dateText: "text-white",
    accent: "text-pink",
    hoverBorder: "group-hover:[border-top-color:#ff2d9b]",
  },
  {
    id: "aurora",
    title: "Aurora",
    artist: "Aurora",
    speakers: ["Aurora"],
    category: "concerts",
    genre: "Ambient Cosmique",
    genreId: "dark-ambient",
    origin: "NO",
    day: "DIM",
    dateLabel: "DIM 26",
    startsAt: "2027-01-26T04:00:00+01:00",
    endsAt: "2027-01-26T05:30:00+01:00",
    time: "04:00",
    duration: "1H30",
    stage: "Sanctuaire de Glace",
    ...commonLocation,
    latitude: 49.7621,
    longitude: 4.7185,
    description:
      "Ambient cosmique et longues nappes lumineuses pour accompagner les dernieres heures de la nuit.",
    image: "/event_1.png",
    dateBg: "bg-pink",
    dateText: "text-white",
    accent: "text-pink",
    hoverBorder: "group-hover:[border-top-color:#ff2d9b]",
  },
  {
    id: "degel",
    title: "Degel",
    artist: "Degel",
    speakers: ["Degel"],
    category: "concerts",
    genre: "Live Techno",
    genreId: "techno",
    origin: "FR",
    day: "DIM",
    dateLabel: "DIM 26",
    startsAt: "2027-01-26T06:00:00+01:00",
    endsAt: "2027-01-26T07:30:00+01:00",
    time: "06:00",
    duration: "1H30",
    stage: "Scene Glacier",
    ...commonLocation,
    latitude: 49.763,
    longitude: 4.7202,
    description:
      "Un live techno progressif qui marque la fin du festival et le retour de la lumiere sur Fatal Fields.",
    image: "/event_3.png",
    dateBg: "bg-pink",
    dateText: "text-white",
    accent: "text-pink",
    hoverBorder: "group-hover:[border-top-color:#ff2d9b]",
  },
];

export function getFallbackEvent(eventId: string) {
  return fallbackFestivalEvents.find((event) => event.id === eventId);
}
